function try_p3(method, varargin)

persistent flBtns fig distance offStopColor onStopColor;
persistent offDoorColor onDoorColor onColor offColor axesH numFloor;
persistent model Stopbtn stop_val Openbtn;
    switch method
        case 'init'
            
            %setting up the figure (canvas)
            fig = figure('Name','Stateflow Elevators', 'DoubleBuffer', 'on'); 
            ratioXY = 600/200;
            set(fig,'Position',[80 150 500 500]);   
            axesH = axes('Color','w', ...
                            'XLim',[1 400], ...
                            'YLim',[1 200], ...
                            'DataAspectRatio',[1 1 1], ...
                            'XTick',[], ...
                            'YTick',[], ...
                            'Position',[0 1/8 1 0.8]);
            % Customize and setup floor,buttons,signs,elevator
            model = 'a2_p3';
            numFloor = 4;
            flBtns = zeros(numFloor, 1);
            offColor = 'w';
            onColor = 'c';
            offDoorColor= 'k';
            onDoorColor= 'r'; %[1 0.3 0];
            onStopColor = [1 0.3 0];
            offStopColor = [0.6 0 0];
            stop_val = 0;
            distance = 100;
            btnSize = 20;
            signSize = 20;
            % Draw each floor level, the floor number sign, and the elevator request button
            for f = 1:numFloor
                floorBaseY = distance*(f-1);
                btnPosX = 50/2-btnSize/2;
                btnPosY = floorBaseY + distance/3;
                signPosX = btnPosX + 2*btnSize;
                signPosY = btnPosY;

                % Elevator request buttons
                flBtns(f) = rectangle('Parent',axesH, ...
                                        'Position',[btnPosY btnPosX btnSize btnSize], ...
                                        'FaceColor',offColor, ...
                                        'ButtonDownFcn',...
                                        ['try_p3(''on'',' num2str(f) ')']);
               % Floor number signs
                text('Parent',axesH, ...
                     'Position',[signPosY signPosX], ...
                     'String',num2str(f), ...
                     'BackgroundColor','k', ...
                     'Color','w', ...
                     'FontName','FixedWidth', ...
                     'FontSize',signSize, ...
                     'FontWeight','bold');
            end
            Stopbtn = text( 'Parent',axesH, ...
                            'Position',[190 130], ...
                            'String','STOP', ...
                            'BackgroundColor',offStopColor, ...
                            'Color','w', ...
                            'FontSize',8, ...
                            'VerticalAlignment','bottom', ...
                            'HorizontalAlignment','right', ...
                            'EdgeColor','k', ...
                            'ButtonDownFcn','try_p3 on stop');
            Openbtn = text('Parent',axesH, ...
                         'Position',[50 130], ...
                         'String','OPEN', ...
                         'BackgroundColor',offDoorColor, ...
                         'Color','w', ...
                         'FontSize',8, ...
                         'VerticalAlignment','bottom', ...
                         'HorizontalAlignment','right', ...
                         'EdgeColor','k');     
        case 'on'
                 if(varargin{1} <= numFloor)
                    actv = flBtns(varargin{1});
                    set(actv,'FaceColor',onColor);
                    set_param([model '/pressed'],'value',num2str(varargin{1}));
                    call_event = get_param([model '/call'],'value');
                    set_param([model '/call'],'value',num2str(~str2double(call_event)));
                 end
                 switch varargin{1}
                     case 'stop'
                         if (stop_val == 0)
                             actv = Stopbtn;
                             set(actv,'BackgroundColor',onStopColor);
                             set_param([model '/stop'],'value','1');
                             stop_val = 1;
                         else
                             try_p3('off','stop');
                         end
                 end
        case 'off'
            switch varargin{1}
                case 'stop'
                    actv = Stopbtn;
                    set(actv,'BackgroundColor',offStopColor);
                    set_param([model '/stop'],'value','0');
                    stop_val = 0;
            end
        case 'open'
            actv = Openbtn;
            set(actv,'BackgroundColor',onDoorColor);
            set_param([model '/door'],'value','0');
        case 'close'
            actv = Openbtn;
            set(actv,'BackgroundColor',offDoorColor);
            set_param([model '/door'],'value','1');
    end
    
